### ISSUE TITLE
Problem while using with mapbox_gl plugin

### ISSUE THREAD

**Issue by Satendra124** [eopeter/flutter_mapbox_navigation#110] opened 2021-03-01 07:15 UTC
While using mapbox_gl flutter package and this package together there is this error:

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Annotation found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$1 found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$1$1 found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$MapClickResolver found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.BuildConfig found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Circle found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CircleElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CircleManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CircleOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.ConvertUtils found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CoreElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.DraggableAnnotationController found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.DraggableAnnotationController$1 found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.DraggableAnnotationController$AnnotationMoveGestureListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Fill found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.FillElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.FillManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.FillOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Line found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.LineElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.LineManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.LineOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnAnnotationClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnAnnotationDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnAnnotationLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnCircleClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnCircleDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnCircleLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnFillClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnFillDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnFillLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnLineClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnLineDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnLineLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnSymbolClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnSymbolDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnSymbolLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Options found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Symbol found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)
  Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 29s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by luis901101** [comment] 2021-03-17 20:58
I have the same problem

**Comment by luis901101** [comment] 2021-03-17 21:04
This is a duplicate of [issue 62](https://github.com/eopeter/flutter_mapbox_navigation/issues/62)
Here there is a [fix](https://github.com/eopeter/flutter_mapbox_navigation/issues/62#issuecomment-685203144)

**Closed** 2023-05-24 06:53 UTC
Labels: no-issue-activity
