### ISSUE TITLE
Mapbox is not working after migrating to null safety flutter_mapbox_navigation@0.0.26

### ISSUE THREAD

**Issue by moolsbytheway** [eopeter/flutter_mapbox_navigation#145] opened 2021-09-19 23:03 UTC
Hello eopeter,
Let me fist think you for making this amazing project.
And let you know that any comment or guiding that you provide will be helpful in my case (because i have an app in beta testing blocked by this issue)

Recently i migrated my project to Null Safety and it was dependent on `flutter_mapbox_navigation` version `0.0.19`

So i needed to migrate to the Null Safety version of the package which i assume is `0.0.26`

The navigation view doesn't work anymore, nor the map view.

I thought it's maybe something wrong with my project so i cloned yours and tried to start the example provided as is (i just changed the mapbox tokens)

These screenshots are from your project's example (same issue in mine also)

The navigation view is like this:
![image](https://user-images.githubusercontent.com/21090828/133945615-ee85268d-5908-40e4-880b-a8ff030217ea.png)

And these two exceptions shows up 
![image](https://user-images.githubusercontent.com/21090828/133945631-b06a2983-55c6-47b8-a978-1ca5567d0d63.png)

I noticed something strange in this class, 
i started a debug session and sometimes the object `json` doesn't have the structure you are waiting for `eventType` and `data` fields are missing and the structure looks like `RouteProgressEvent` class.

Something else, your model is different from the model provided in the 1.2.0 navigation ui api
https://docs.mapbox.com/android/navigation/api/1.2.0/libnavigation-base/-base/com.mapbox.navigation.base.trip.model/-route-progress/

![image](https://user-images.githubusercontent.com/21090828/133945783-2381a539-4601-41d2-af68-be60e74b26eb.png)

Any help will be appreciated.

Thank you.

**Comment by ShejaEddy** [comment] 2021-09-20 14:24
In my case it can't even open once on android, It crashes as soon as the page is opened
```
I/huribus.map_bo( 9854): Background concurrent copying GC freed 15252(1113KB) AllocSpace objects, 4(208KB) LOS objects, 49% free, 3MB/6MB, paused 5.277ms total 119.614ms
E/MapboxNavNative( 9854): User defined HTTP service instance not provided from the module implementation.
E/MapboxNavNative( 9854): Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@d96dfde
E/MapboxNavNative( 9854): but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@d96dfde
E/MapboxNavNative( 9854): Are you calling HttpServiceFactory.setUserDefined() correctly?
E/AndroidRuntime( 9854): FATAL EXCEPTION: main
E/AndroidRuntime( 9854): Process: com.shuribus.map_box, PID: 9854
E/AndroidRuntime( 9854): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common14OfflineService16registerObserverERKNSt6__ndk110shared_ptrINS0_22OfflineServiceObserverEEE" referenced by "/data/app/com.shuribus.map_box-vWwa6rDZFuIZiRC2JiqDyA==/lib/arm/libnavigator-android.so"...
E/AndroidRuntime( 9854):        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
E/AndroidRuntime( 9854):        at java.lang.System.loadLibrary(System.java:1669)
E/AndroidRuntime( 9854):        at com.mapbox.navigator.NavNativeStaticInitializer$Companion.loadRequiredDependencies(NavNativeStaticInitializer.kt:45)
E/AndroidRuntime( 9854):        at com.mapbox.navigator.NavNativeStaticInitializer.loadRequiredDependencies(Unknown Source:2)
E/AndroidRuntime( 9854):        at com.mapbox.navigator.Navigator.<clinit>(Navigator.java:13)
E/AndroidRuntime( 9854):        at com.mapbox.navigation.navigator.internal.NavigatorLoader.createNavigator(NavigatorLoader.kt:24)
E/AndroidRuntime( 9854):        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.create(MapboxNativeNavigatorImpl.kt:59)
E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.NavigationComponentProvider.createNativeNavigator(NavigationComponentProvider.kt:31)
E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:168)
E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/AndroidRuntime( 9854):        at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
E/AndroidRuntime( 9854):        at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/AndroidRuntime( 9854):        at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
E/AndroidRuntime( 9854):        at android.app.Dialog.show(Dialog.java:302)
E/AndroidRuntime( 9854):        at android.app.Presentation.show(Presentation.java:249)
E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime( 9854):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 9854):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 9854):        at android.os.MessageQueue.next(MessageQueue.java:326)
E/AndroidRuntime( 9854):        at android.os.Looper.loop(Looper.java:160)
E/AndroidRuntime( 9854):        at android.app.ActivityThread.main(ActivityThread.java:6724)
E/AndroidRuntime( 9854):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9854):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9854):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by eopeter** [comment] 2021-09-20 14:34
On the GitHub read me did you execute Step 3 in the Android Configuration?

**Comment by ShejaEddy** [comment] 2021-09-20 14:52
Yes I did.

```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1Ijoic2hlamFlZGR5MDUiLCJhIjoiY2t0cmlobzFyMGw3MzJ2a2dkczAxZnp0aSJ9.xwM1tgpoPiP3RN7UIrMuHg
```

**Comment by moolsbytheway** [comment] 2021-09-20 17:54
@eopeter same here

**Comment by ShejaEddy** [comment] 2021-09-21 10:59
I managed to get my app started, Wow! It feels really good.
Now I'm facing the same issue as @moolsbytheway [
![image](https://user-images.githubusercontent.com/49254767/134159226-d394fc36-e65c-434a-a959-ce954d083994.png)
]

**Comment by moolsbytheway** [comment] 2021-09-21 12:15
@eopeter any idea ? any actions that i can take to resolve this ? (beside re-implementing eveything with the last version of navigation-ui )

**Comment by ShejaEddy** [comment] 2021-09-21 13:05
I think I @moolsbytheway  is right, the problem is originating here at this Function 
```
RouteEvent _parseRouteEvent(String jsonString) {
    RouteEvent event;
    var map = json.decode(jsonString); // The response is varying differently to the expected model response (EventType &  data: // which is sometimes missing from the response
    var progressEvent = RouteProgressEvent.fromJson(map); // The response model has changed, This model won't work //anymore.
    if (progressEvent.isProgressEvent!) {
      event = RouteEvent(
          eventType: MapBoxEvent.progress_change, data: progressEvent);
    } else
      event = RouteEvent.fromJson(map);
    return event;
  }
```
I don't think I can be of much help but this is the cause of the problem. Please @eopeter  help us. @moolsbytheway Have you found a workaround?

**Comment by elFallino** [comment] 2021-09-24 19:29
I have the same repeating warning:
W/Mbgl    (10182): {Worker 2}[Style]: Attempt to set an invalid property value -0.041080)

I've seen this before. This is the alpha-value of the LocationComponent pule (that "own location"- marker on the map).
It has that pulsing circle around that is fading out. 

This issue is mentioned here: 
https://github.com/mapbox/mapbox-gl-native-android/issues/611
https://github.com/mapbox/mapbox-gl-native-android/pull/625

I guess using the latest mapbox libraries should fix that as well as disabling that pulse.

**Comment by ShejaEddy** [comment] 2021-09-27 06:57
Please @elFallino  can you show how to do that. An example would be nice.

**Comment by BrianRigii** [comment] 2021-11-15 09:43
> Please @elFallino can you show how to do that. An example would be nice.

Hey @elFallino  kindlt assist

**Comment by aramisromero89** [comment] 2021-11-25 19:44
> In my case it can't even open once on android, It crashes as soon as the page is opened
> 
> ```
> I/huribus.map_bo( 9854): Background concurrent copying GC freed 15252(1113KB) AllocSpace objects, 4(208KB) LOS objects, 49% free, 3MB/6MB, paused 5.277ms total 119.614ms
> E/MapboxNavNative( 9854): User defined HTTP service instance not provided from the module implementation.
> E/MapboxNavNative( 9854): Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@d96dfde
> E/MapboxNavNative( 9854): but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@d96dfde
> E/MapboxNavNative( 9854): Are you calling HttpServiceFactory.setUserDefined() correctly?
> E/AndroidRuntime( 9854): FATAL EXCEPTION: main
> E/AndroidRuntime( 9854): Process: com.shuribus.map_box, PID: 9854
> E/AndroidRuntime( 9854): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common14OfflineService16registerObserverERKNSt6__ndk110shared_ptrINS0_22OfflineServiceObserverEEE" referenced by "/data/app/com.shuribus.map_box-vWwa6rDZFuIZiRC2JiqDyA==/lib/arm/libnavigator-android.so"...
> E/AndroidRuntime( 9854):        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
> E/AndroidRuntime( 9854):        at java.lang.System.loadLibrary(System.java:1669)
> E/AndroidRuntime( 9854):        at com.mapbox.navigator.NavNativeStaticInitializer$Companion.loadRequiredDependencies(NavNativeStaticInitializer.kt:45)
> E/AndroidRuntime( 9854):        at com.mapbox.navigator.NavNativeStaticInitializer.loadRequiredDependencies(Unknown Source:2)
> E/AndroidRuntime( 9854):        at com.mapbox.navigator.Navigator.<clinit>(Navigator.java:13)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.navigator.internal.NavigatorLoader.createNavigator(NavigatorLoader.kt:24)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.create(MapboxNativeNavigatorImpl.kt:59)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.NavigationComponentProvider.createNativeNavigator(NavigationComponentProvider.kt:31)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:168)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
> E/AndroidRuntime( 9854):        at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
> E/AndroidRuntime( 9854):        at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
> E/AndroidRuntime( 9854):        at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
> E/AndroidRuntime( 9854):        at android.app.Dialog.show(Dialog.java:302)
> E/AndroidRuntime( 9854):        at android.app.Presentation.show(Presentation.java:249)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
> E/AndroidRuntime( 9854):        at android.os.MessageQueue.nativePollOnce(Native Method)
> E/AndroidRuntime( 9854):        at android.os.MessageQueue.next(MessageQueue.java:326)
> E/AndroidRuntime( 9854):        at android.os.Looper.loop(Looper.java:160)
> E/AndroidRuntime( 9854):        at android.app.ActivityThread.main(ActivityThread.java:6724)
> E/AndroidRuntime( 9854):        at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 9854):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> E/AndroidRuntime( 9854):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
> ```

how did you solve this?? I'm facing same issue.

**Comment by aramisromero89** [comment] 2021-11-25 19:45
> In my case it can't even open once on android, It crashes as soon as the page is opened
> 
> ```
> I/huribus.map_bo( 9854): Background concurrent copying GC freed 15252(1113KB) AllocSpace objects, 4(208KB) LOS objects, 49% free, 3MB/6MB, paused 5.277ms total 119.614ms
> E/MapboxNavNative( 9854): User defined HTTP service instance not provided from the module implementation.
> E/MapboxNavNative( 9854): Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@d96dfde
> E/MapboxNavNative( 9854): but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@d96dfde
> E/MapboxNavNative( 9854): Are you calling HttpServiceFactory.setUserDefined() correctly?
> E/AndroidRuntime( 9854): FATAL EXCEPTION: main
> E/AndroidRuntime( 9854): Process: com.shuribus.map_box, PID: 9854
> E/AndroidRuntime( 9854): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common14OfflineService16registerObserverERKNSt6__ndk110shared_ptrINS0_22OfflineServiceObserverEEE" referenced by "/data/app/com.shuribus.map_box-vWwa6rDZFuIZiRC2JiqDyA==/lib/arm/libnavigator-android.so"...
> E/AndroidRuntime( 9854):        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
> E/AndroidRuntime( 9854):        at java.lang.System.loadLibrary(System.java:1669)
> E/AndroidRuntime( 9854):        at com.mapbox.navigator.NavNativeStaticInitializer$Companion.loadRequiredDependencies(NavNativeStaticInitializer.kt:45)
> E/AndroidRuntime( 9854):        at com.mapbox.navigator.NavNativeStaticInitializer.loadRequiredDependencies(Unknown Source:2)
> E/AndroidRuntime( 9854):        at com.mapbox.navigator.Navigator.<clinit>(Navigator.java:13)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.navigator.internal.NavigatorLoader.createNavigator(NavigatorLoader.kt:24)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.create(MapboxNativeNavigatorImpl.kt:59)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.NavigationComponentProvider.createNativeNavigator(NavigationComponentProvider.kt:31)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:168)
> E/AndroidRuntime( 9854):        at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
> E/AndroidRuntime( 9854):        at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
> E/AndroidRuntime( 9854):        at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
> E/AndroidRuntime( 9854):        at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
> E/AndroidRuntime( 9854):        at android.app.Dialog.show(Dialog.java:302)
> E/AndroidRuntime( 9854):        at android.app.Presentation.show(Presentation.java:249)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
> E/AndroidRuntime( 9854):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/AndroidRuntime( 9854):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
> E/AndroidRuntime( 9854):        at android.os.MessageQueue.nativePollOnce(Native Method)
> E/AndroidRuntime( 9854):        at android.os.MessageQueue.next(MessageQueue.java:326)
> E/AndroidRuntime( 9854):        at android.os.Looper.loop(Looper.java:160)
> E/AndroidRuntime( 9854):        at android.app.ActivityThread.main(ActivityThread.java:6724)
> E/AndroidRuntime( 9854):        at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 9854):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> E/AndroidRuntime( 9854):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
> ```

@ShejaEddy how did you solve this?? I'm facing same issue.

**Comment by eopeter** [comment] 2021-11-26 00:26
I’ll update the MapBox library to the latest and push up.

**Comment by moolsbytheway** [comment] 2021-11-26 12:18
@eopeter thank you, please drop a comment here when the ugrade is done.

**Comment by BrianRigii** [comment] 2021-12-07 05:30
@eopeter  where are we on this

**Comment by eopeter** [comment] 2021-12-07 05:37
Library changed significantly on MapBox 2.0 so taking longer to upgrade.

**Comment by eopeter** [comment] 2021-12-07 05:40
Will be able to push out the update by this weekend.

**Comment by BrianRigii** [comment] 2021-12-07 05:42
Greate, looking forward to it

**Comment by eopeter** [comment] 2021-12-14 00:00
Will provide update on this soon...jammed

**Comment by moolsbytheway** [comment] 2021-12-20 08:19
ping...

**Comment by moolsbytheway** [comment] 2021-12-20 08:20
@eopeter any news ?

**Comment by eopeter** [comment] 2021-12-21 13:17
my vacation begins today so hoping to close this out. Experiencing a weird issue where the map tiles won't load when embedded. Hoping to get resolution on it today.

**Comment by moolsbytheway** [comment] 2021-12-21 14:02
Thank you so much for the effort, i appreciate it.

**Comment by DevPianist** [comment] 2021-12-24 23:08
Waiting the update, thank you!

**Comment by MarkLinovy** [comment] 2022-01-08 19:13
@eopeter Also waiting for the new version :)

I would love to assist you. But I wouldn't want to start a fork when you are just a few minutes short of releasing it. So I would appreciate an update on this Issue.

**Comment by moolsbytheway** [comment] 2022-02-12 20:51
@eopeter any news ? 😢

**Comment by eopeter** [comment] 2022-02-12 20:53
This should be fixed in the latest. The library is migrated to MapBox Android 10 and once I deploy it, should address a lot of the open bugs

**Comment by moolsbytheway** [comment] 2022-02-12 20:55
Thank you for the reactivity. 
Do you have any estimated release date 😭  ?

**Comment by otorresd** [comment] 2022-10-19 18:37
Any news?

**Comment by eopeter** [comment] 2023-04-26 21:51
c

**Closed by eopeter** 2023-04-26 21:51 UTC
